edit files

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,4 +1,4 @@
-name: Terraform Safe Apply on Yandex Cloud
+name: Terraform Apply + Ansible Provisioning
 
 on:
   push:
@@ -20,6 +20,9 @@ jobs:
       TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
       TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
       TF_VAR_zone: ${{ secrets.YC_ZONE }}
+      TF_VAR_s3_access_key: ${{ secrets.S3_ACCESS_KEY }}
+      TF_VAR_s3_secret_key: ${{ secrets.S3_SECRET_KEY }}
+      TF_VAR_get_hosts: "true"
 
     steps:
       - name: Checkout repository
@@ -37,26 +40,29 @@ jobs:
         run: terraform validate
 
       - name: Terraform Plan
-        run: terraform plan -out=tfplan -detailed-exitcode || exit_code=$?
+        id: plan
+        run: |
+          terraform plan -out=tfplan -detailed-exitcode || exit_code=$?
+          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
         continue-on-error: true
 
-      - name: Check Plan Result
-        id: check_plan
+      - name: Check Plan Exit Code
+        id: check
         run: |
-          if [ "$exit_code" == "0" ]; then
+          if [ "${{ steps.plan.outputs.exit_code }}" == "0" ]; then
             echo "No changes to apply."
             exit 0
-          elif [ "$exit_code" == "1" ]; then
-            echo "Error during plan"
+          elif [ "${{ steps.plan.outputs.exit_code }}" == "1" ]; then
+            echo "Terraform plan failed."
             exit 1
-          elif [ "$exit_code" == "2" ]; then
-            echo "Changes detected"
+          elif [ "${{ steps.plan.outputs.exit_code }}" == "2" ]; then
+            echo "Changes detected."
           else
-            echo "Unknown exit code: $exit_code"
+            echo "Unknown exit code: ${{ steps.plan.outputs.exit_code }}"
             exit 1
           fi
 
-      - name: Check for Deletions
+      - name: Check for Destroy in Plan
         run: |
           terraform show -json tfplan | jq -e '
             .resource_changes[]? | select(.change.actions | index("delete"))
@@ -72,3 +78,18 @@ jobs:
 
       - name: Terraform Apply
         run: terraform apply -auto-approve tfplan
+
+      - name: Get Bastion IP
+        id: bastion_ip
+        run: |
+          ip=$(terraform output -raw bastion_ip)
+          echo "ip=$ip" >> $GITHUB_OUTPUT
+
+      - name: Copy hosts.yaml to Bastion
+        uses: appleboy/scp-action@v0.1.7
+        with:
+          host: ${{ steps.bastion_ip.outputs.ip }}
+          username: ubuntu
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          source: terraform/ansible/hosts.yaml
+          target: /home/ubuntu/
